-- The discharge summary as a STRUCTURED record, not a document written from scratch.
--
-- WHY THIS EXISTS. Until now a WardMate discharge summary was a pure projection of
-- `observations` — lib/discharge.ts assembled the pilot unit's paper template on every render
-- and stored nothing. The General Surgery Discharge Protocol v1.0 changes the product: the
-- discharge summary becomes the FINAL STRUCTURED COMPILATION of the admission, in NABH/ABDM
-- section order, with two sections (Clinical Course, Relevant Investigations) generated by the
-- AI and then reviewed and APPROVED by the resident before the summary can be finalised.
--
-- So there needs to be somewhere to keep the resident's verified, edited and approved content —
-- the parts that are NOT derivable from observations (the synthesised course, the chosen
-- investigation lines, the primary-care and patient actions, the condition variables, the
-- authentication) and the approval state that the completeness checks read.
--
-- ONE ROW PER PATIENT. The row is created lazily the first time the discharge workspace saves
-- anything; a patient with no row simply gets a freshly COMPILED draft every time the workspace
-- opens, exactly as the old projection behaved. Nothing about existing patients breaks: this is
-- a new table, no column is added to `patients`, so `current_patients` does not need rebuilding
-- (see the note in supabase/schema.sql section 6 and CONTEXT.md section 5).
--
-- Every content column is jsonb with a fixed shape (documented in lib/discharge-entities.ts).
-- ABDM compatibility in v1 is STRUCTURAL — the entities and the section set are the standard
-- ones — not a FHIR export; that is a later patch.
--
-- Safe to run more than once.

begin;

create table if not exists discharge_summaries (
  id           uuid primary key default gen_random_uuid(),
  patient_id   uuid not null references patients (id) on delete cascade,
  -- Denormalised from the patient, the same way entries/observations carry it, so every row
  -- policy is a single is_ward_member() check and the formats/formulary lookups do not need a
  -- join back through patients.
  ward_id      uuid not null references wards (id) on delete cascade,

  -- One structured discharge per patient. A second "prepare discharge" simply reopens the
  -- existing row.
  unique (patient_id),

  -- --- The protocol's core discharge entities (protocol section 19), each with a consistent
  -- --- inner shape carrying provenance + approval where it is an AI section. See
  -- --- lib/discharge-entities.ts for the exact field list of each.
  -- ---
  -- --- Every column defaults to jsonb null, meaning "the resident has not touched this section" —
  -- --- the workspace then shows the freshly COMPILED value (lib/discharge-compile.ts). The first
  -- --- save writes the section's real shape (an object, or an array that may legitimately be
  -- --- empty), and from then on the stored value wins over the compiled one.
  indication_for_admission jsonb not null default 'null'::jsonb,
  encounter                jsonb not null default 'null'::jsonb,
  diagnoses                jsonb not null default 'null'::jsonb,
  procedures               jsonb not null default 'null'::jsonb,
  clinical_course          jsonb not null default 'null'::jsonb,
  relevant_investigations  jsonb not null default 'null'::jsonb,
  histopathology           jsonb not null default 'null'::jsonb,
  medications              jsonb not null default 'null'::jsonb,
  condition_at_discharge   jsonb not null default 'null'::jsonb,
  primary_care_actions     jsonb not null default 'null'::jsonb,
  patient_actions          jsonb not null default 'null'::jsonb,
  advice                   jsonb not null default 'null'::jsonb,
  red_flags                jsonb not null default 'null'::jsonb,
  authentication           jsonb not null default 'null'::jsonb,

  -- draft until the resident finalises. Finalising runs the completeness checks server-side and
  -- refuses while any high-priority check is unmet (protocol section 16).
  status       text not null default 'draft' check (status in ('draft', 'finalised')),
  finalised_at timestamptz,
  finalised_by uuid references auth.users (id),

  created_at   timestamptz not null default now(),
  created_by   uuid references auth.users (id),
  -- Set by the server action on every write rather than by a trigger — this project keeps its
  -- write paths visible in application code.
  updated_at   timestamptz not null default now()
);

create index if not exists discharge_summaries_patient_idx on discharge_summaries (patient_id);
create index if not exists discharge_summaries_ward_idx on discharge_summaries (ward_id);

alter table discharge_summaries enable row level security;

-- Exactly the shape of the observations policies (supabase/schema.sql lines 275-285): a member
-- of the owning ward may read and write; row security in Postgres is the real boundary.
drop policy if exists discharge_summaries_read on discharge_summaries;
create policy discharge_summaries_read on discharge_summaries for select using (
  exists (select 1 from patients p where p.id = discharge_summaries.patient_id and public.is_ward_member(p.ward_id))
);

drop policy if exists discharge_summaries_insert on discharge_summaries;
create policy discharge_summaries_insert on discharge_summaries for insert with check (
  exists (select 1 from patients p where p.id = discharge_summaries.patient_id and public.is_ward_member(p.ward_id))
);

drop policy if exists discharge_summaries_update on discharge_summaries;
create policy discharge_summaries_update on discharge_summaries for update using (
  exists (select 1 from patients p where p.id = discharge_summaries.patient_id and public.is_ward_member(p.ward_id))
) with check (
  exists (select 1 from patients p where p.id = discharge_summaries.patient_id and public.is_ward_member(p.ward_id))
);

-- A member may delete the row to reset a draft to a freshly compiled one. A finalised summary
-- is still deletable by design — the record it was built from is untouched, and a summary sent
-- home with the wrong content has to be re-doable.
drop policy if exists discharge_summaries_delete on discharge_summaries;
create policy discharge_summaries_delete on discharge_summaries for delete using (
  exists (select 1 from patients p where p.id = discharge_summaries.patient_id and public.is_ward_member(p.ward_id))
);

grant select, insert, update, delete on discharge_summaries to authenticated;

commit;
