import type { HistoryTree } from "@/lib/history-check/types";
import { BROWSE, commonHpi, DAS_CLINICAL_SURGERY, HAMILTON_BAILEY, HUTCHISONS, MACLEODS, SABISTON, surgicalBackground, val, yn } from "@/content/history-trees/_helpers";

/**
 * SCROTAL SWELLING OR PAIN — v1.0.0. CLINICAL CONTENT: PENDING REVIEW (Sabiston background added, docs/surgical-history.md §9).
 * Adult surgical / urology ward, north India. One question dominates: how suddenly did the pain
 * start, and in whom. Sudden severe pain in an adolescent or young adult is torsion until
 * excluded, and the testis is salvageable only for a few hours. Differentials: testicular
 * torsion, epididymo-orchitis, inguinoscrotal hernia, hydrocele, varicocele, testicular tumour,
 * trauma or haematocele, filarial swelling.
 */
export const scrotalSwellingV1: HistoryTree = {
  id: "scrotal_swelling",
  version: "1.2.0",
  complaint: "Scrotal swelling or pain",
  triggers: ["scrotal swelling", "scrotum swelling", "swelling of scrotum", "testicular pain", "testis pain", "pain in testis", "scrotal pain", "swollen testicle", "testicular swelling", "hydrocele", "varicocele"],
  setting: "Adult surgical / urology ward, north India",
  reviewStatus: "pending_clinician_review",
  reviewedBy: null,
  references: [DAS_CLINICAL_SURGERY, HAMILTON_BAILEY, MACLEODS, HUTCHISONS, BROWSE, SABISTON],
  slots: [
    ...commonHpi("scrotal swelling"),
    val("hpi", "side", "Which side", "Which side is affected — left, right, or both?", ["left", "right", "both", "one side", "bilateral", "unilateral"]),
    val("hpi", "pain_severity", "Pain and how it started", "How severe is the pain?", ["severe pain", "sudden", "suddenly", "gradual", "over days", "mild", "painless", "woke from sleep", "abrupt", "out of 10"], { numeric: true }),
    val("hpi", "swelling_character", "Nature of the swelling", "Does the swelling feel soft, tense or hard, and does it extend up into the groin?", ["soft", "tense", "hard", "cystic", "firm", "can get above", "cannot get above", "bag of worms", "heavy", "irregular"]),
    yn("hpi", "size_variation", "Change in size", "Does the swelling change in size on standing, lying down, coughing, or straining?", ["standing", "lying down", "coughing", "straining", "reduces", "disappears", "increases", "end of day", "varies", "cough impulse"]),
    yn("hpi", "transillumination_history", "Whether it was ever described as fluid-filled", "Was the swelling ever described elsewhere as fluid-filled, or drained before?", ["fluid", "water", "drained", "tapped", "aspirated", "fluid filled", "previously"], { tier: "detailed" }),
    yn("associated", "fever", "Fever", "Any fever or chills?", ["fever", "chills", "rigors", "temperature", "febrile"]),
    yn("associated", "urinary_symptoms", "Burning urine / discharge / stream", "Any burning on passing urine, urethral discharge, or poor stream?", ["burning", "dysuria", "urethral discharge", "poor stream", "frequency", "urgency", "pus"]),
    yn("associated", "nausea_vomiting", "Nausea / vomiting", "Any nausea or vomiting with the pain?", ["nausea", "vomiting", "vomit", "retching"]),
    yn("associated", "abdominal_pain", "Abdominal or groin pain", "Any pain in the lower abdomen or groin, or pain radiating up from the scrotum?", ["lower abdomen", "groin", "radiating", "loin", "flank", "abdominal pain", "inguinal"]),
    yn("associated", "weight_loss_cough", "Weight loss / cough / back pain / breast swelling", "Any weight loss, cough, back pain, or swelling and tenderness of the breasts?", ["weight loss", "cough", "back pain", "breast swelling", "gynaecomastia", "breast tenderness", "haemoptysis", "abdominal lump"], { tier: "detailed" }),
    yn("associated", "infertility_heaviness", "Dragging heaviness / difficulty fathering a child", "Any dragging heaviness in the scrotum, or difficulty in fathering a child?", ["dragging", "heaviness", "infertility", "no children", "dull ache", "end of day", "standing long"], { tier: "detailed" }),
    yn("associated", "limb_swelling", "Swelling of the leg or recurrent attacks of fever", "Any swelling of the leg, thickened skin, or recurrent attacks of fever with the swelling?", ["leg swelling", "thickened skin", "elephantiasis", "recurrent fever", "filaria", "lymphoedema", "attacks"], { tier: "detailed" }),
    // Red flags
    yn("red_flag", "sudden_severe_pain", "Sudden severe pain, especially waking from sleep", "Did severe testicular pain begin abruptly at a definite moment, or wake the patient from sleep?", ["sudden", "abrupt", "severe pain", "woke from sleep", "within minutes", "young", "adolescent", "teenager", "excruciating"], { teach: "Schwartz describes torsion pain starting at a distinct point in time and peaking within hours, against a day or two for epididymo-orchitis; it peaks in adolescents but occurs at any age, so youth is a pointer, not a requirement." }),
    yn("associated", "high_riding_horizontal", "Testis pulled up or lying differently", "Does the affected testis appear pulled up, lying higher, or sitting in a different position from the other side?", ["pulled up", "high riding", "higher", "horizontal", "different position", "retracted", "lying across"], { tier: "detailed", teach: "A testis that has ridden up or changed its lie is the bedside sign that accompanies a twisted cord." }),
    yn("hpi", "previous_similar_episodes", "Previous similar attacks that settled", "Any previous episodes of similar severe pain that settled on their own?", ["previous episodes", "similar pain", "settled", "came and went", "before", "intermittent", "resolved on its own"], { teach: "Previous self-resolving attacks of severe pain describe intermittent twisting, and they raise rather than lower the concern." }),
    yn("red_flag", "trauma", "Injury to the scrotum", "Any injury, blow, or fall onto the scrotum?", ["injury", "trauma", "blow", "kick", "fall", "hit", "accident", "sports"], { teach: "An injury can rupture the testis or bleed into it, and it can also unmask a tumour that was already there." }),
    yn("red_flag", "hard_painless_mass", "Hard lump within the testis", "Is there a hard lump within the testis itself, painful or not?", ["hard", "painless", "lump", "grown", "over weeks", "increasing", "heavy", "irregular", "no pain"], { teach: "Schwartz treats a testicular mass as malignant until proven otherwise and notes most patients present with pain or a mass, so pain does not make a tumour less likely." }),
    yn("red_flag", "skin_changes_sepsis", "Redness spreading / black skin / severe illness", "Any spreading redness, blackening of the scrotal skin, foul discharge, or severe illness with fever?", ["spreading redness", "blackening", "black", "necrosis", "foul discharge", "crepitus", "severe illness", "toxic", "gangrene", "diabetic"], { teach: "Blackening or rapidly spreading redness of scrotal skin marks a necrotising infection, where the delay is counted in hours." }),
    yn("red_flag", "irreducible_hernia", "A groin swelling now irreducible with vomiting", "Was there a groin swelling that used to go back and now will not, with pain and vomiting?", ["irreducible", "not going back", "used to reduce", "vomiting", "tense", "painful", "obstructed", "constipation"], { teach: "A previously reducible inguinoscrotal swelling that becomes irreducible and painful raises trapped bowel in the sac." }),
    yn("exposure", "sexual_exposure", "Sexual exposure", "Any recent unprotected sexual contact or a new partner?", ["unprotected", "new partner", "sexual contact", "sti", "multiple partners", "discharge"]),
    yn("exposure", "undescended_testis", "Undescended testis / previous scrotal surgery", "Was either testis ever undescended, or has there been previous surgery on the groin or scrotum?", ["undescended", "not descended", "orchidopexy", "previous surgery", "hernia repair", "childhood surgery", "empty scrotum"]),
    yn("exposure", "mumps_tb", "Mumps / tuberculosis", "Any recent mumps, parotid swelling, or past tuberculosis?", ["mumps", "parotid", "swelling of cheek", "tuberculosis", "tb", "koch", "att"], { tier: "detailed" }),
    yn("exposure", "filaria_endemic", "Living in a filaria-endemic area", "Does the patient live in or come from an area where filaria is common?", ["filaria", "endemic", "village", "area", "mosquito", "elephantiasis", "recurrent attacks"], { tier: "detailed" }),
    // S. Das, A Manual on Clinical Surgery, 13th ed. (docs/surgical-history.md §10)
    yn("hpi", "pain_trigger_strain", "What the pain started with", "Did the pain start while straining at stool, lifting something heavy, or during intercourse?", ["straining", "lifting heavy", "during intercourse", "after sex", "while passing stool", "exertion", "at rest", "no trigger"], { tier: "detailed", teach: "Das links torsion to straining, lifting or intercourse through sudden cremaster contraction; many torsions begin at rest or in sleep, so a missing trigger does not lower the concern." }),
    yn("associated", "haematuria_new_varicocele", "Varicocele appearing in adult life", "Has the varicocele appeared recently in adult life?", ["blood in urine", "haematuria", "red urine", "appeared quickly", "recent varicocele", "left side", "no blood in urine", "right side", "does not empty lying down"], { teach: "A varicocele that appears in adult life, sits on the right, or stays full on lying down asks about a kidney or retroperitoneal mass pressing on the vein; Das adds blood in the urine with a left kidney growth." }),
    yn("associated", "upper_abdominal_lump", "Lump in the upper abdomen", "Has a lump been noticed in the upper abdomen or around the navel?", ["lump in abdomen", "abdominal lump", "upper abdomen", "near the navel", "epigastric lump", "no abdominal lump"], { tier: "detailed", teach: "Das notes a testicular growth may go unnoticed and first show as an upper-abdominal lump from spread to the lymph nodes." }),
    yn("exposure", "urethral_injury_stricture", "Fall astride, urethral stricture or a burst abscess near the urethra", "Was there a fall astride something, a known narrowing of the urine passage, or an abscess near the urethra that burst before the swelling?", ["fall astride", "straddle injury", "stricture", "narrow stream for years", "abscess near urethra", "periurethral", "swelling after passing urine", "no injury"], { tier: "detailed", teach: "Das gives urethral injury or a burst periurethral abscess on a stricture as the usual story behind urine leaking into the scrotum, which spreads quickly." }),
    yn("exposure", "occupation_soot_tar_oil", "Work with soot, tar or oil", "Has the work involved years of contact with soot, tar, or mineral oil?", ["soot", "chimney", "tar", "mineral oil", "machine oil", "factory", "mechanic", "no such exposure"], { tier: "detailed", teach: "Das links long occupational contact with soot, tar or oil to cancer of the scrotal skin." }),
    // Hamilton Bailey's Demonstrations of Physical Signs, 19th ed. (docs/surgical-history.md §11)
    yn("exposure", "recurrent_uti_antibiotics", "Repeated antibiotic courses for urine infection", "Has the patient had repeated courses of antibiotics for urine infections that kept coming back?", ["repeated antibiotics", "recurrent urine infection", "uti again and again", "many courses", "burning urine for months", "no recurrent infection"], { tier: "detailed", teach: "Hamilton Bailey notes genitourinary tuberculosis is often treated with several antibiotic courses for supposed recurrent urine infection before tuberculosis is suspected." }),
    yn("associated", "scrotal_sinus", "Discharging opening on the scrotum", "Is there an opening on the scrotum that keeps discharging?", ["discharging sinus", "opening on scrotum", "pus from scrotum", "keeps draining", "wound that does not heal", "no discharge"], { tier: "detailed", teach: "Hamilton Bailey describes a discharging scrotal sinus in severe tuberculous infection of the epididymis, which turns the history towards tuberculosis." }),
    yn("exposure", "perianal_source", "Abscess or boil near the anus before the scrotal swelling", "Was there an abscess or boil near the anus or in the perineum before the scrotal redness began?", ["perianal abscess", "boil near anus", "perineal abscess", "piles operation", "anal pain before", "no perianal problem"], { tier: "detailed", teach: "Hamilton Bailey names the large bowel, urinary tract and genital skin as the usual sources of Fournier's gangrene, so the story looks for where the infection entered." }),
    // Schwartz's Principles of Surgery, 11th ed. (docs/surgical-history.md §12)
    yn("exposure", "testis_cancer_history", "Previous or family testicular cancer", "Has the patient had a testicular cancer before, or has a father or brother had one?", ["testicular cancer", "testis cancer", "previous orchidectomy", "father", "brother", "no testicular cancer"], { teach: "Schwartz names undescended testis, a family history and a previous testicular cancer as the established risk factors for a new testicular tumour." }),
    yn("associated", "incomplete_emptying", "Incomplete emptying or a recent catheter", "Has there been difficulty emptying the bladder, or a catheter or instrument passed recently?", ["incomplete emptying", "retention", "catheter", "catheterised", "cystoscopy", "instrumentation", "no catheter"], { teach: "Schwartz separates sexually acquired infection in younger men from urinary infection in older men, where poor bladder emptying or instrumentation is the usual source." }),
    ...surgicalBackground({ acute: true, omit: ["surg_weight_loss"] }),
  ],
  differentials: [
    { id: "torsion", name: "Testicular torsion", pointers: ["sudden_severe_pain", "high_riding_horizontal", "previous_similar_episodes", "nausea_vomiting"], discriminators: ["sudden_severe_pain", "high_riding_horizontal", "previous_similar_episodes", "nausea_vomiting", "fever", "urinary_symptoms", "pain_severity", "pain_trigger_strain"] },
    { id: "epididymo_orchitis", name: "Epididymo-orchitis", pointers: ["fever", "urinary_symptoms", "sexual_exposure", "pain_severity"], discriminators: ["fever", "urinary_symptoms", "sexual_exposure", "pain_severity", "onset_mode", "sudden_severe_pain", "mumps_tb", "recurrent_uti_antibiotics", "scrotal_sinus", "incomplete_emptying"] },
    { id: "hernia", name: "Inguinoscrotal hernia", pointers: ["size_variation", "irreducible_hernia", "swelling_character"], discriminators: ["size_variation", "irreducible_hernia", "swelling_character", "abdominal_pain", "undescended_testis"] },
    { id: "hydrocele", name: "Hydrocele", pointers: ["swelling_character", "transillumination_history"], discriminators: ["swelling_character", "transillumination_history", "pain_severity", "size_variation", "duration"] },
    { id: "varicocele", name: "Varicocele", pointers: ["swelling_character", "infertility_heaviness", "size_variation"], discriminators: ["swelling_character", "infertility_heaviness", "size_variation", "side", "pain_severity", "haematuria_new_varicocele"] },
    { id: "tumour", name: "Testicular tumour", pointers: ["hard_painless_mass", "weight_loss_cough", "undescended_testis", "testis_cancer_history"], discriminators: ["hard_painless_mass", "weight_loss_cough", "undescended_testis", "swelling_character", "trauma", "upper_abdominal_lump", "testis_cancer_history"] },
    { id: "trauma_haematocele", name: "Trauma / haematocele", pointers: ["trauma", "pain_severity", "swelling_character"], discriminators: ["trauma", "pain_severity", "swelling_character", "onset_mode", "hard_painless_mass"] },
    { id: "filarial", name: "Filarial scrotal swelling", pointers: ["limb_swelling", "filaria_endemic"], discriminators: ["limb_swelling", "filaria_endemic", "swelling_character", "duration", "fever", "scrotal_sinus"] },
    { id: "necrotising_infection", name: "Necrotising scrotal infection", pointers: ["skin_changes_sepsis", "fever"], discriminators: ["skin_changes_sepsis", "fever", "pain_severity", "onset_mode", "urethral_injury_stricture", "perianal_source"] },
  ],
  output: {
    durationSlot: "duration",
    hpiOrder: ["onset", "duration", "onset_mode", "side", "pain_severity", "swelling_character", "size_variation", "progression", "prior_treatment", "prior_investigations"],
  },
};
