import type { HistoryTree } from "@/lib/history-check/types";
import { commonHpi, FISHMAN, HUTCHISONS, MACLEODS, NTEP, val, yn } from "@/content/history-trees/_helpers";

/**
 * PROBLEM WHILE ON TB TREATMENT — v1.0.0. CLINICAL CONTENT: PENDING CLINICIAN REVIEW.
 * Pulmonary medicine ward, north India, where a patient on anti-tubercular treatment is
 * admitted with jaundice, vomiting, a rash, blurred vision, or simply "not getting better".
 * Three questions run underneath the whole history: which regimen, which month, and how many
 * doses were really taken; what the diagnosis rested on in the first place; and whether the
 * drugs, the bacteria or the host explains the new problem.
 * Differentials: drug-induced liver injury, not improving / possible drug resistance
 * (MDR/RR-TB), non-adherence or interruption, paradoxical reaction / IRIS in HIV, optic neuritis
 * from ethambutol, peripheral neuropathy, skin rash / hypersensitivity, joint pain from
 * pyrazinamide, hearing loss or kidney injury from injectables in DR-TB regimens, wrong diagnosis,
 * neuropsychiatric drug effects.
 */
export const tbTreatmentProblemV1: HistoryTree = {
  id: "tb_treatment_problem",
  version: "1.0.0",
  complaint: "Problem while on TB treatment",
  triggers: ["on att", "att induced", "att induced hepatitis", "att hepatitis", "dili", "on tb treatment", "tb treatment", "tb ki dawai", "not improving on att", "att side effect", "att reaction", "mdr tb", "rr tb", "dr tb", "drug resistant tb", "defaulted att", "left att"],
  setting: "Pulmonary medicine ward, north India",
  reviewStatus: "pending_clinician_review",
  reviewedBy: null,
  references: [NTEP, FISHMAN, MACLEODS, HUTCHISONS],
  slots: [
    ...commonHpi("problem"),
    val("hpi", "main_problem", "What the problem is", "What is the new problem — vomiting, yellow eyes, rash, blurred vision, tingling, joint pain, or not getting better?", ["vomiting", "nausea", "yellow eyes", "jaundice", "rash", "itching", "blurred vision", "tingling", "joint pain", "not improving", "fever persists", "weight loss", "new swelling"]),
    val("hpi", "regimen_type", "Regimen", "Which TB treatment is the patient on — the usual first-line combination or a drug-resistant regimen — and which drugs are named on the strip, box or card?", ["first line", "fdc", "fixed dose", "4fdc", "3fdc", "hrze", "isoniazid", "rifampicin", "pyrazinamide", "ethambutol", "bedaquiline", "linezolid", "levofloxacin", "moxifloxacin", "delamanid", "clofazimine", "cycloserine", "kanamycin", "amikacin", "injection", "dr regimen", "mdr regimen", "shorter regimen", "longer regimen", "private doctor"], { teach: "The drugs actually in the strip decide which side effects are possible, and patients on private treatment may be on something other than the programme regimen." }),
    val("hpi", "phase_month", "Phase and month", "When was treatment started, which month is it now, and is the patient in the intensive or continuation phase?", ["month", "months", "started on", "intensive phase", "continuation phase", "ip", "cp", "first month", "second month", "extended", "weeks"], { numeric: true, teach: "Most liver injury appears in the first two months, while a patient still not better at the end of the intensive phase is a different question." }),
    val("hpi", "adherence", "Doses missed", "How many doses have been missed, has treatment ever been stopped and for how long, and why?", ["missed", "missed doses", "stopped", "left in between", "interrupted", "defaulted", "irregular", "took regularly", "no missed doses", "ran out", "could not afford", "vomited tablets", "felt better"], { teach: "A patient who is not improving has often not been taking the drugs, and interruption is also how resistance is made." }),
    yn("hpi", "registration", "Nikshay and DOTS registration", "Is the patient registered on Nikshay or with a DOTS centre, who supervises the doses, and is the treatment card or Nikshay id available?", ["nikshay", "nikshay id", "dots", "dots centre", "treatment card", "supporter", "asha", "registered", "government", "private", "not registered", "99dots"], { tier: "detailed" }),
    val("hpi", "diagnosis_basis", "What the diagnosis rested on", "What site of TB was diagnosed, and on what — sputum smear, CBNAAT, culture, biopsy, x-ray alone, or a trial of treatment?", ["pulmonary", "extrapulmonary", "lymph node", "pleural", "abdominal", "spine", "sputum positive", "sputum negative", "smear", "cbnaat", "genexpert", "truenat", "culture", "biopsy", "x-ray only", "clinical", "trial of att", "empirical"], { teach: "Treatment started without a microbiological or tissue result leaves open the possibility that the illness was never tuberculosis." }),
    val("hpi", "cbnaat_result", "CBNAAT, LPA, culture results", "What did CBNAAT or TrueNat show — MTB detected, rifampicin resistance detected or not — and were line probe assay, culture or drug-susceptibility results received?", ["cbnaat", "genexpert", "truenat", "mtb detected", "mtb not detected", "rif resistance detected", "rif resistance not detected", "rif indeterminate", "lpa", "line probe", "culture", "dst", "drug susceptibility", "pending", "not done"], { teach: "A rifampicin-resistance result, or one still pending, changes how a patient who is not improving is read." }),
    val("hpi", "response_so_far", "Response so far", "Since starting treatment, have the cough, fever, appetite and weight improved, stayed the same, or become worse, and what did the follow-up sputum show?", ["better", "improved", "same", "worse", "weight gained", "weight lost", "fever gone", "fever persists", "follow up sputum", "sputum converted", "still positive", "appetite"], { teach: "Weight and follow-up sputum are the programme's own markers of response, and a patient who has not gained weight needs the reason found." }),
    // Associated
    yn("associated", "liver_symptoms", "Nausea, vomiting, yellow eyes, dark urine", "Any nausea, vomiting, loss of appetite, pain in the right upper abdomen, yellow eyes, or dark urine since starting treatment?", ["nausea", "vomiting", "loss of appetite", "right upper abdomen", "pain in abdomen", "yellow eyes", "jaundice", "dark urine", "high coloured urine", "peela"], { teach: "Nausea and loss of appetite usually come before the eyes turn yellow, so they are asked for even when jaundice is absent." }),
    yn("associated", "tingling_numbness", "Tingling or burning of feet and hands", "Any tingling, burning, or numbness of the feet or hands?", ["tingling", "burning feet", "numbness", "pins and needles", "jhunjhuni", "feet burning", "hands numb"], { teach: "Tingling of the feet on treatment is asked about because nerve damage is more likely with alcohol, diabetes, poor nutrition, pregnancy or HIV." }),
    yn("associated", "rash_itch", "Itching or rash", "Any itching or rash, when did it start, and was there fever with it?", ["itching", "rash", "khujli", "red spots", "hives", "fever with rash", "after tablets"]),
    yn("associated", "joint_pain_pza", "Joint pain", "Any joint pain, or a hot swollen big toe or other joint?", ["joint pain", "big toe", "swollen joint", "gout", "painful joints", "knee pain", "arthralgia"]),
    yn("associated", "hearing_kidney", "Ringing ears, hearing loss, unsteadiness, less urine", "Any ringing in the ears, reduced hearing, unsteady walking, or reduced urine, particularly with injections in the regimen?", ["ringing in ears", "tinnitus", "hearing loss", "cannot hear", "unsteady", "imbalance", "less urine", "reduced urine", "swelling", "injections"], { teach: "Injectable drugs in older drug-resistant regimens can damage hearing, balance and kidneys, and early hearing loss is only found by asking." }),
    yn("associated", "mood_behaviour", "Mood, sleep, behaviour or fits", "Any low mood, poor sleep, strange behaviour, thoughts of self-harm, or fits since the treatment started?", ["low mood", "sad", "not sleeping", "insomnia", "strange behaviour", "irritable", "self harm", "suicidal", "fits", "seizure", "confusion", "psychosis"], { tier: "detailed", teach: "Some drugs in drug-resistant regimens affect mood and behaviour, and thoughts of self-harm are only heard if asked." }),
    // Exposure
    val("exposure", "hiv_status", "HIV status and ART", "Has the patient been tested for HIV, what was the result, and if positive, when was ART started in relation to TB treatment?", ["hiv", "hiv positive", "hiv negative", "not tested", "art", "antiretroviral", "cd4", "started art", "weeks after", "plhiv"], { teach: "In someone with HIV who starts ART during TB treatment, a new worsening a few weeks later raises the immune system recovering and flaring, not only failure." }),
    yn("exposure", "diabetes_status", "Diabetes", "Is the patient diabetic, and how well controlled has the sugar been during treatment?", ["diabetes", "diabetic", "sugar", "uncontrolled sugar", "hba1c", "insulin", "not diabetic"], { teach: "Diabetes slows the response to TB treatment and adds nerve damage of its own, so control is asked about." }),
    yn("exposure", "liver_risks", "Alcohol, liver disease, other medicines", "Does the patient drink alcohol, have known liver disease or hepatitis B or C, or take any other medicines, herbal or ayurvedic preparations?", ["alcohol", "daru", "liver disease", "hepatitis b", "hepatitis c", "hbsag", "cirrhosis", "herbal", "ayurvedic", "desi dawai", "paracetamol", "other medicines"]),
    val("exposure", "previous_tb_episodes", "Previous TB treatment", "Has the patient been treated for TB before, how many times, and was the course completed?", ["previous tb", "treated before", "second time", "retreatment", "relapse", "completed", "left in between", "cured", "first episode"], { teach: "Earlier treatment, and especially an earlier course left in between, raises the chance of drug resistance." }),
    val("exposure", "contacts", "Household contacts", "Who lives in the household, are there children under five, have they been screened, and is anyone else known to have TB or drug-resistant TB?", ["household", "family members", "children", "under five", "screened", "contact", "preventive therapy", "tpt", "drug resistant contact", "mdr contact", "no contacts"], { teach: "Contact with someone known to have drug-resistant TB changes how a patient not improving is read, and household children need screening in their own right." }),
    // Red flags
    yn("red_flag", "liver_failure_signs", "Deep jaundice, drowsiness, bleeding", "Is the patient deeply jaundiced, drowsy or confused, bleeding from anywhere, or vomiting everything?", ["deep jaundice", "drowsy", "confused", "altered", "bleeding", "vomiting everything", "cannot keep anything down", "abdominal swelling", "encephalopathy"], { teach: "Jaundice with drowsiness or bleeding marks liver injury that has begun to fail, which progresses over hours to days." }),
    yn("red_flag", "severe_skin_reaction", "Blistering or peeling rash, mouth or eye sores", "Is there blistering or peeling of the skin, sores in the mouth or eyes, or high fever with the rash?", ["blisters", "peeling", "skin coming off", "mouth ulcers", "mouth sores", "red eyes", "sores in eyes", "high fever", "widespread rash"], { teach: "Peeling skin with mouth or eye sores marks a severe drug reaction, which is separate from a simple itch." }),
    yn("red_flag", "vision_change", "Blurring or colour vision change", "Any blurring of vision, difficulty telling red from green, or loss of vision in one or both eyes?", ["blurred vision", "blurring", "colour vision", "red green", "cannot see", "dim vision", "loss of vision", "one eye", "both eyes"], { teach: "Blurring or loss of colour vision on treatment raises damage to the optic nerve, which recovers best when found early." }),
    yn("red_flag", "new_worsening", "New breathlessness, new swelling, headache or stiff neck", "Since treatment began, any new breathlessness, new or enlarging neck swellings, headache with neck stiffness, weakness of limbs, or blood in the cough?", ["new breathlessness", "enlarging", "new swelling", "neck nodes", "headache", "neck stiffness", "vomiting", "weakness of limbs", "blood in sputum", "worse after starting"], { teach: "A new site or worsening after treatment began can be a paradoxical reaction, resistance or another disease, and all three need prompt attention." }),
  ],
  differentials: [
    { id: "dili", name: "Drug-induced liver injury", pointers: ["liver_symptoms", "liver_failure_signs"], discriminators: ["liver_symptoms", "liver_failure_signs", "phase_month", "liver_risks", "regimen_type"] },
    { id: "drug_resistance", name: "Not improving / possible drug resistance (MDR/RR-TB)", pointers: ["previous_tb_episodes", "cbnaat_result", "contacts"], discriminators: ["cbnaat_result", "previous_tb_episodes", "adherence", "response_so_far", "contacts"] },
    { id: "non_adherence", name: "Non-adherence or interruption", pointers: ["adherence"], discriminators: ["adherence", "registration", "response_so_far", "liver_risks", "phase_month"] },
    { id: "paradoxical_iris", name: "Paradoxical reaction / IRIS in HIV", pointers: ["new_worsening", "hiv_status"], discriminators: ["hiv_status", "new_worsening", "phase_month", "response_so_far", "adherence"] },
    { id: "optic_neuritis", name: "Optic neuritis from ethambutol", pointers: ["vision_change"], discriminators: ["vision_change", "regimen_type", "phase_month", "diabetes_status"] },
    { id: "peripheral_neuropathy", name: "Peripheral neuropathy", pointers: ["tingling_numbness"], discriminators: ["tingling_numbness", "diabetes_status", "liver_risks", "hiv_status", "regimen_type"] },
    { id: "drug_hypersensitivity", name: "Skin rash / drug hypersensitivity", pointers: ["rash_itch", "severe_skin_reaction"], discriminators: ["rash_itch", "severe_skin_reaction", "phase_month", "hiv_status", "liver_symptoms"] },
    { id: "pza_arthralgia", name: "Joint pain from pyrazinamide", pointers: ["joint_pain_pza"], discriminators: ["joint_pain_pza", "regimen_type", "phase_month", "liver_risks"] },
    { id: "injectable_toxicity", name: "Hearing loss or kidney injury from injectables", pointers: ["hearing_kidney"], discriminators: ["hearing_kidney", "regimen_type", "phase_month", "diabetes_status"] },
    { id: "neuropsychiatric", name: "Neuropsychiatric drug effects", pointers: ["mood_behaviour"], discriminators: ["mood_behaviour", "regimen_type", "liver_risks", "hiv_status"] },
    { id: "wrong_diagnosis", name: "Wrong diagnosis (not tuberculosis)", pointers: ["diagnosis_basis", "response_so_far"], discriminators: ["diagnosis_basis", "cbnaat_result", "response_so_far", "adherence", "hiv_status"] },
  ],
  output: {
    durationSlot: "duration",
    hpiOrder: ["main_problem", "onset", "duration", "onset_mode", "progression", "regimen_type", "phase_month", "adherence", "registration", "diagnosis_basis", "cbnaat_result", "response_so_far", "prior_treatment", "prior_investigations"],
  },
};
