import type { HistoryTree } from "@/lib/history-check/types";
import { commonHpi, FISHMAN, GINA, GOLD, HUTCHISONS, MACLEODS, val, yn } from "@/content/history-trees/_helpers";

/**
 * WHEEZE / TIGHT CHEST — v1.0.0. CLINICAL CONTENT: PENDING CLINICIAN REVIEW.
 * Pulmonary medicine ward, north India, where most wheeze on admission is an asthma or COPD
 * flare, and COPD here follows years of bidi or cigarette smoke or of cooking over a chulha.
 * Two questions run underneath the whole history: is the noise really coming from the small
 * airways rather than the throat or the heart, and how close is the patient to tiring out.
 * Differentials: asthma exacerbation, COPD exacerbation, allergic bronchopulmonary
 * aspergillosis, cardiac asthma / heart failure, upper airway obstruction or foreign body,
 * bronchiectasis, anaphylaxis, tropical pulmonary eosinophilia, vocal cord dysfunction.
 */
export const wheezeV1: HistoryTree = {
  id: "wheeze",
  version: "1.0.0",
  complaint: "Wheeze / tight chest",
  triggers: ["wheeze", "wheezing", "wheezy", "tight chest", "chest tightness", "tightness in chest", "whistling in chest", "seeti ki awaz", "asthma", "asthma attack", "acute asthma", "dama", "copd", "copd exacerbation", "aecopd", "bronchospasm"],
  setting: "Pulmonary medicine ward, north India",
  reviewStatus: "pending_clinician_review",
  reviewedBy: null,
  references: [FISHMAN, GINA, GOLD, MACLEODS, HUTCHISONS],
  slots: [
    ...commonHpi("wheeze"),
    val("hpi", "wheeze_pattern", "Pattern of wheeze", "Does the wheeze come in attacks with normal breathing in between, or is the patient never fully free of it?", ["attacks", "episodes", "comes and goes", "normal in between", "free in between", "always", "persistent", "every day", "never free", "since childhood", "for years"], { teach: "Attacks with full recovery in between sit with asthma, while breathlessness that never fully settles sits with fixed airway narrowing." }),
    yn("hpi", "night_symptoms", "Night waking", "Does the wheeze or cough wake the patient at night or early in the morning?", ["at night", "wakes up", "night cough", "early morning", "raat ko", "sleep disturbed", "night waking"]),
    val("hpi", "wheeze_triggers", "Triggers", "What brings the wheeze on — dust, cold air, smoke, a cold, exercise, strong smells, work, or a painkiller or blood-pressure tablet?", ["dust", "cold air", "winter", "smoke", "cold", "exercise", "running", "smell", "perfume", "agarbatti", "pollen", "at work", "painkiller", "aspirin", "blood pressure tablet", "better on holidays"], { teach: "A named trigger, and wheeze that eases away from work, turn a vague history of attacks into something that can be avoided." }),
    val("hpi", "inhaler_use", "Inhalers used", "Which inhalers are used, how often is the reliever needed in a week, and is the preventer taken every day or only during attacks?", ["inhaler", "pump", "reliever", "preventer", "blue inhaler", "rotacap", "rotahaler", "nebulisation", "nebulizer", "only when needed", "daily", "stopped inhaler", "no inhaler"], { teach: "How often the reliever is reached for is the patient's own measure of how controlled the airways have been." }),
    val("hpi", "inhaler_technique", "Inhaler technique", "Which device is used, with or without a spacer, and has anyone watched the patient use it?", ["spacer", "mdi", "metered dose", "dry powder", "rotacap", "capsule", "technique", "shown how", "never shown", "spacer not used"], { tier: "detailed", teach: "A preventer that seems not to work is often one that never reaches the lungs because of how the device is used." }),
    yn("hpi", "stridor_vs_wheeze", "Noise on breathing in or out", "Is the noise heard mainly on breathing in and from the throat, or on breathing out and from the chest?", ["breathing in", "breathing out", "from throat", "from chest", "stridor", "croaky", "harsh noise", "musical"], { teach: "A harsh noise on breathing in from the throat points to the upper airway, which the airway drugs for wheeze do not open." }),
    yn("hpi", "sputum_change", "Change in sputum, fever or cold before", "Has the sputum increased or changed colour, and was there a cold, sore throat or fever before this episode?", ["yellow sputum", "green sputum", "more sputum", "purulent", "fever", "cold", "sore throat", "viral", "sputum changed"], { teach: "An infection is the commonest thing that tips a stable airway disease into a flare, and a change in sputum is how it shows." }),
    // Associated
    yn("associated", "atopy", "Allergy, childhood asthma, family history", "Any asthma in childhood, sneezing or running nose with the seasons, eczema, or asthma or allergy in the family?", ["childhood asthma", "since childhood", "allergic rhinitis", "sneezing", "running nose", "eczema", "allergy", "family history", "mother has asthma", "father has asthma"]),
    yn("associated", "cardiac_wheeze", "Heart disease, lying flat, swollen feet", "Any known heart disease, breathlessness on lying flat, waking gasping at night, or swelling of the feet?", ["heart disease", "heart attack", "valve", "lying flat", "pillows", "gasping at night", "swelling of feet", "pink frothy", "palpitations"], { teach: "Wheeze that starts in later life with breathlessness on lying flat and swollen feet raises fluid in the lungs from the heart." }),
    yn("associated", "brown_plugs", "Brown plugs in sputum, repeated shadows", "Has the patient coughed up brown or black plugs, or been told of shadows on the x-ray that come and go?", ["brown plugs", "black plugs", "plugs", "casts", "shadows", "fleeting", "changing x-ray", "aspergillus", "fungal"], { tier: "detailed", teach: "Brown plugs and shadows that move on repeated films in someone with asthma raise an allergic reaction to a fungus in the airways." }),
    yn("associated", "copious_sputum", "Daily large amounts of sputum", "Does the patient bring up a large amount of sputum every day, for years, with repeated chest infections?", ["copious", "cupful", "large amount", "every day", "for years", "foul", "repeated chest infections", "posture", "mornings"], { teach: "Daily large volumes of sputum over years raise permanently widened airways, which can wheeze as well as rattle." }),
    yn("associated", "night_cough_eosinophilia", "Night cough with low fever, filaria or worm history", "Any dry cough mainly at night with low-grade fever, weight loss, a past blood count showing high eosinophils, or past filaria?", ["night cough", "low grade fever", "eosinophils", "eosinophilia", "high tlc", "filaria", "filarial", "worms", "weight loss"], { tier: "detailed", teach: "Night cough and wheeze with very high eosinophils in a blood count raise a reaction to filarial infection that mimics asthma." }),
    yn("associated", "throat_tightness_vcd", "Throat tightness, voice change in attacks", "During attacks, is the tightness felt in the throat rather than the chest, with a change in voice, and does it switch on and off suddenly?", ["throat tightness", "tight throat", "voice change", "choking feeling in throat", "sudden on and off", "stress", "anxiety", "normal between attacks", "inhalers never help"], { tier: "detailed", teach: "Tightness felt at the throat that switches on and off and never responds to inhalers raises the vocal cords closing, not the airways." }),
    yn("associated", "choking_episode", "Choking episode", "Did the wheeze begin with a choking or coughing fit while eating, or is one side of the chest noisier?", ["choking", "while eating", "swallowed", "something went down", "coughing fit", "one side", "foreign body", "seed", "peanut"], { teach: "Wheeze that began with a choking fit, and is louder on one side, raises something lodged in an airway." }),
    yn("associated", "allergen_rash", "Hives, lip swelling after food, sting or injection", "Did the wheeze start within minutes of a food, sting, medicine or injection, with itching, hives, or swelling of the lips or face?", ["hives", "urticaria", "itching", "rash", "lip swelling", "face swelling", "after injection", "after food", "sting", "bee", "within minutes", "allergic reaction"], { teach: "Wheeze arriving within minutes of an exposure, with skin or lip swelling, raises a whole-body allergic reaction rather than an airway flare." }),
    // Exposure
    yn("exposure", "tobacco_smoke", "Smoking", "Does the patient smoke bidi, cigarettes or hookah, since when and how many a day, or has he or she quit?", ["smoking", "smoker", "bidi", "cigarette", "hookah", "chillum", "packs", "per day", "years", "quit", "ex smoker", "never smoked"], { teach: "Years of smoking make fixed airway narrowing more likely than asthma, and the amount smoked is part of that reading." }),
    yn("exposure", "biomass_smoke", "Cooking smoke", "Has the patient cooked for years over a chulha on wood, dung cakes or crop waste, and in a room with poor ventilation?", ["chulha", "wood", "dung cakes", "uple", "crop waste", "cooking smoke", "biomass", "angithi", "kitchen smoke", "no ventilation", "lpg"], { teach: "Years of cooking smoke cause fixed airway narrowing in people who have never smoked, and are easily missed if not asked." }),
    val("exposure", "steroid_courses", "Steroid courses and admissions", "How many courses of steroid tablets or injections, and how many hospital admissions for breathing, in the past year?", ["steroid", "steroids", "prednisolone", "wysolone", "courses", "admissions", "admitted", "last year", "emergency visits", "no admissions"], { numeric: true, teach: "Repeated steroid courses and admissions in the past year mark an airway disease that flares badly and often." }),
    // Red flags
    yn("red_flag", "cannot_speak", "Too breathless to speak", "Is the patient too breathless to finish a sentence, sitting forward, or unable to lie down?", ["cannot speak", "cannot complete sentences", "words only", "sitting forward", "cannot lie down", "tripod", "gasping", "too breathless to talk"], { teach: "Being unable to finish a sentence is the bedside mark of a severe attack, before any number is available." }),
    yn("red_flag", "drowsy_blue", "Drowsy, confused, blue or exhausted", "Is the patient drowsy, confused, blue at the lips, exhausted, or has the wheeze gone quiet while the breathing is still hard?", ["drowsy", "confused", "blue lips", "cyanosis", "exhausted", "tired out", "silent chest", "quiet chest", "not responding"], { teach: "Drowsiness, blueness or a chest that goes quiet mean the patient is tiring, which comes before the breathing stops." }),
    yn("red_flag", "prior_icu_niv", "Past ICU, BiPAP or ventilator", "Has the patient ever been in ICU, put on BiPAP, or on a ventilator for breathing?", ["icu", "intensive care", "bipap", "niv", "ventilator", "intubated", "tube in mouth", "never in icu"], { teach: "A past attack that needed intensive care, BiPAP or a ventilator is the strongest marker of an attack that can turn fatal." }),
    yn("red_flag", "airway_swelling", "Swelling of tongue or throat, drooling", "Any swelling of the tongue or throat, drooling, inability to swallow saliva, or a harsh noise on breathing in?", ["tongue swelling", "throat swelling", "drooling", "cannot swallow", "saliva", "stridor", "noisy breathing in", "hoarse"], { teach: "Swelling of the tongue or throat, or drooling, threatens the upper airway and changes how urgently everything else happens." }),
    yn("red_flag", "sudden_chest_pain", "Sudden one-sided chest pain", "Did the breathlessness worsen suddenly with a sharp pain on one side of the chest?", ["sudden", "sharp pain", "one side", "chest pain", "pleuritic", "worse suddenly", "pain on breathing"], { teach: "A sudden worsening with one-sided sharp pain in a patient with airway disease raises air leaking around the lung." }),
  ],
  differentials: [
    { id: "asthma_exacerbation", name: "Asthma exacerbation", pointers: ["wheeze_pattern", "atopy", "night_symptoms", "wheeze_triggers"], discriminators: ["wheeze_pattern", "atopy", "night_symptoms", "wheeze_triggers", "inhaler_use", "steroid_courses"] },
    { id: "copd_exacerbation", name: "COPD exacerbation", pointers: ["tobacco_smoke", "biomass_smoke", "sputum_change"], discriminators: ["tobacco_smoke", "biomass_smoke", "sputum_change", "wheeze_pattern", "prior_icu_niv"] },
    { id: "abpa", name: "Allergic bronchopulmonary aspergillosis", pointers: ["brown_plugs", "atopy"], discriminators: ["brown_plugs", "atopy", "copious_sputum", "steroid_courses", "wheeze_pattern"] },
    { id: "cardiac_asthma", name: "Cardiac asthma / heart failure", pointers: ["cardiac_wheeze"], discriminators: ["cardiac_wheeze", "night_symptoms", "atopy", "wheeze_pattern", "tobacco_smoke"] },
    { id: "upper_airway_obstruction", name: "Upper airway obstruction or foreign body", pointers: ["stridor_vs_wheeze", "choking_episode", "airway_swelling"], discriminators: ["stridor_vs_wheeze", "choking_episode", "airway_swelling", "onset_mode", "inhaler_use"] },
    { id: "bronchiectasis", name: "Bronchiectasis", pointers: ["copious_sputum", "sputum_change"], discriminators: ["copious_sputum", "sputum_change", "brown_plugs", "duration", "tobacco_smoke"] },
    { id: "anaphylaxis", name: "Anaphylaxis", pointers: ["allergen_rash", "airway_swelling"], discriminators: ["allergen_rash", "airway_swelling", "onset_mode", "atopy", "wheeze_triggers"] },
    { id: "tropical_pulmonary_eosinophilia", name: "Tropical pulmonary eosinophilia", pointers: ["night_cough_eosinophilia"], discriminators: ["night_cough_eosinophilia", "night_symptoms", "atopy", "duration", "inhaler_use"] },
    { id: "vocal_cord_dysfunction", name: "Vocal cord dysfunction", pointers: ["throat_tightness_vcd", "stridor_vs_wheeze"], discriminators: ["throat_tightness_vcd", "stridor_vs_wheeze", "inhaler_use", "wheeze_pattern", "onset_mode"] },
  ],
  output: {
    durationSlot: "duration",
    hpiOrder: ["onset", "duration", "wheeze_pattern", "onset_mode", "progression", "night_symptoms", "wheeze_triggers", "stridor_vs_wheeze", "sputum_change", "inhaler_use", "inhaler_technique", "prior_treatment", "prior_investigations"],
  },
};
