import type { ExamChecklist, ExamItem } from "@/lib/history-check/exam-types";
import { HUTCHISONS, MACLEODS, rce } from "@/content/history-trees/_helpers";

/**
 * GENERAL PHYSICAL EXAMINATION — v1.0.0. CLINICAL CONTENT: REVIEWED.
 *
 * The head-to-toe survey done before any system examination, in the order it is taught in
 * Indian medical colleges (Hutchison's / Macleod's / bedside long-case format). Each item
 * says how to elicit the sign and what a positive finding is associated with. Nothing here
 * names a treatment, and nothing tells the reader what the patient has.
 */
const item = (
  id: string,
  label: string,
  how: string,
  significance: string,
  extra: Partial<Pick<ExamItem, "normal" | "tier">> = {}
): ExamItem => ({ id, label, how, significance, ...extra });

const d = { tier: "detailed" as const };

export const generalPhysicalV1: ExamChecklist = {
  id: "general_physical",
  version: "1.0.0",
  title: "General physical examination",
  setting: "Adult medicine ward, north India",
  reviewStatus: "reviewed",
  reviewedBy: "Dr. Anubhav, General Surgery — 2026-09-26",
  references: [
    HUTCHISONS,
    MACLEODS,
    rce("Is this patient hypovolemic?", 1999, "10086438"),
    rce("Does this patient have abnormal central venous pressure?", 1996, "8594245"),
    rce("Does this patient have clubbing?", 2001, "11466101"),
    rce("Does this patient have a goiter?", 1995, "7861577"),
    rce("Does this patient have splenomegaly?", 1993, "8411607"),
    { title: "Anthropometric reference for Asian Indians (BMI cut-offs)", source: "Consensus statement, Indian Journal of Medical Research / Ministry of Health", year: 2009 },
    { title: "Bates' Guide to Physical Examination and History Taking", source: "Wolters Kluwer (textbook)" },
  ],
  sections: [
    {
      id: "preliminaries",
      title: "Before you touch the patient",
      intro: "Introduce yourself, explain, take consent, ensure privacy and a chaperone where appropriate, wash hands, and examine from the patient's right side in good light. Observe the whole patient and the bedside (oxygen, drips, catheter, sputum cup, inhalers) before starting.",
      items: [
        item("consciousness", "Consciousness and orientation", "Speak to the patient. Ask name, place, and time (date or day). Note whether the patient is alert, drowsy but rousable to voice, rousable only to pain, or unresponsive. Record the Glasgow Coma Scale (eye, verbal, motor) if not fully alert.", "Drowsiness or disorientation is seen in sepsis, metabolic derangement (sugars, sodium, urea, liver failure), hypoxia, hypercapnia, intracranial events, drug or alcohol effects.", { normal: "Conscious, oriented to time, place and person." }),
        item("general_condition", "General condition", "Stand at the foot of the bed and form an impression: does the patient look well, unwell, or seriously ill (toxic)? Look for distress, sweating, restlessness, ability to speak in sentences.", "A toxic look (flushed, sweating, restless, rapid breathing) is seen in severe sepsis and shock; the impression from the foot of the bed often precedes the numbers.", { normal: "Looks comfortable, not in distress." }),
        item("decubitus", "Decubitus (position in bed)", "Note how the patient is lying: flat and comfortable, propped up on pillows, sitting forward, lying on one side with knees drawn up, or unable to lie still.", "Sitting propped up is seen in heart failure and severe airway disease; lying still is seen with peritoneal irritation; rolling about is seen in colicky pain; curled on the side with neck extended is seen in meningeal irritation.", { normal: "Lying comfortably in bed, any position." }),
        item("build", "Build", "Judge the skeletal frame and overall size against age and sex: short or tall stature, and proportion of limbs to trunk (arm span versus height, upper to lower segment ratio if indicated).", "Tall stature with long limbs is seen in Marfan's habitus; short stature in endocrine or skeletal disorders; disproportion points to a skeletal rather than a nutritional cause.", { normal: "Average build." }),
        item("nutrition", "Nutrition", "Look at muscle bulk (temporalis, deltoid, thenar), subcutaneous fat (triceps skinfold, over the ribs), and mid-arm circumference. Compare weight and BMI with the Asian-Indian cut-offs. Ask about recent weight change.", "Wasting is seen in tuberculosis, malignancy, HIV, malabsorption, chronic organ failure and poor intake; central obesity carries metabolic and cardiovascular risk.", { normal: "Adequately nourished." }),
        item("facies", "Facies", "Look at the face as a whole for a recognisable pattern: puffy, moon-shaped, mask-like, anxious, staring, cachectic, or asymmetric.", "A moon face is seen with long steroid exposure; puffy dull facies in thyroid deficiency; mask-like face in Parkinsonism; staring prominent eyes in thyroid excess; leonine facies in leprosy; a toxic flushed face in high fever.", d),
        item("attitude", "Attitude and behaviour", "Note posture, cooperation, agitation, apathy, and whether the patient makes eye contact and follows instructions.", "Agitation or apathy is seen in encephalopathy, alcohol withdrawal, hypoxia, severe pain and psychiatric illness.", d),
        item("speech", "Speech", "Listen while taking the history: volume, clarity, fluency, and whether words are slurred, hoarse, or nasal.", "Slurring is seen in cerebellar disease, stroke and intoxication; hoarseness in laryngeal or recurrent laryngeal nerve involvement; nasal speech in palatal weakness.", d),
        item("gait", "Gait", "If safe, watch the patient walk to and from the bed, turn, and if possible walk heel-to-toe.", "A broad-based unsteady gait is seen in cerebellar disease; a shuffling gait with reduced arm swing in Parkinsonism; a high-stepping gait with foot drop; a waddling gait in proximal muscle weakness; a hemiplegic circumducting gait after stroke.", d),
        item("hygiene_odour", "Hygiene and odour", "Note personal hygiene, oral hygiene, and any odour on the breath: fruity, ammoniacal, musty, alcohol, or foul.", "A fruity smell is seen in ketosis; an ammoniacal smell in uraemia; a musty sweet smell (fetor hepaticus) in liver failure; foul breath with lung abscess or dental sepsis.", d),
        item("apparent_age", "Apparent versus stated age", "Compare how old the patient looks with the stated age.", "Looking older than the stated age is seen in chronic illness, smoking, chronic organ failure and malnutrition; looking younger in hypogonadism.", d),
      ],
    },
    {
      id: "vitals",
      title: "Vital signs",
      intro: "Measure, do not estimate. Record the actual numbers with the time, and repeat abnormal readings yourself.",
      items: [
        item("pulse_rate", "Pulse — rate", "Place three fingers over the radial artery at the wrist, thumb side, with the forearm slightly pronated. Count for a full minute if the rhythm is irregular, otherwise 30 seconds doubled. Count the apex at the same time if the pulse is irregular, to detect a pulse deficit.", "Tachycardia is seen in fever, pain, anxiety, anaemia, hypovolaemia, heart failure, thyroid excess and arrhythmia. Bradycardia is seen in heart block, drug effect, raised intracranial pressure, thyroid deficiency and in athletes; a relatively slow pulse for the fever is described in enteric fever.", { normal: "60 to 100 per minute." }),
        item("pulse_rhythm", "Pulse — rhythm", "Feel for regularity over a full minute. Decide whether irregularity is regularly irregular (a repeating pattern) or irregularly irregular (no pattern), and whether it disappears with exercise or breath-holding.", "An irregularly irregular pulse is seen in atrial fibrillation and multiple ectopics; a regularly irregular pulse in second-degree heart block and coupled ectopics; sinus arrhythmia varies with breathing and is normal in the young.", { normal: "Regular." }),
        item("pulse_volume", "Pulse — volume", "Judge the amplitude of the pulse wave under the fingers: low, normal or high. Compare both radials.", "A low-volume (thready) pulse is seen in shock, hypovolaemia, severe aortic stenosis and heart failure; a high-volume (bounding) pulse in fever, anaemia, thyroid excess, aortic regurgitation and carbon dioxide retention.", { normal: "Normal volume." }),
        item("pulse_character", "Pulse — character", "Feel the carotid or brachial for the shape of the upstroke and downstroke: slow-rising, collapsing (lift the arm above the head with your palm across the forearm and feel the tap), alternating strong and weak beats, or a double peak.", "A slow-rising pulse is seen in aortic stenosis; a collapsing (water-hammer) pulse in aortic regurgitation, patent ductus and high-output states; pulsus alternans in severe left ventricular failure; pulsus paradoxus (fall of more than 10 mmHg in systolic pressure on inspiration) in cardiac tamponade and severe asthma.", d),
        item("vessel_wall", "Pulse — condition of the vessel wall", "Occlude the radial artery proximally and distally with two fingers and roll the empty segment under a third finger. A palpable, cord-like, tortuous artery is abnormal.", "A thickened or tortuous vessel wall is seen in long-standing hypertension and atherosclerosis in the elderly.", d),
        item("radio_delay", "Radio-radial and radio-femoral delay", "Feel both radial pulses simultaneously; then feel a radial and a femoral pulse together. Any delay or weakness on one side is abnormal.", "Radio-femoral delay is seen in coarctation of the aorta; radio-radial delay or inequality in aortic dissection, subclavian stenosis and Takayasu's arteritis.", d),
        item("peripheral_pulses", "Peripheral pulses", "Feel and compare the brachial, carotid (one at a time), femoral, popliteal, posterior tibial (behind the medial malleolus) and dorsalis pedis (lateral to the extensor hallucis tendon) pulses on both sides.", "Absent or weak peripheral pulses are seen in peripheral arterial disease, embolism, dissection and vasculitis; absence in one limb with pain and pallor points to acute limb ischaemia.", d),
        item("bp", "Blood pressure", "Patient seated or lying, arm at heart level, correct cuff size (bladder covering about 80% of arm circumference), after 5 minutes of rest. Inflate while palpating the radial pulse to estimate systolic, then auscultate over the brachial artery inflating 30 mmHg above that. Deflate slowly (2 to 3 mmHg per second). First sound is systolic; disappearance of sounds is diastolic. Record the arm and position.", "A raised reading on repeated measurement is seen in hypertension; a low reading in shock, dehydration, adrenal insufficiency and drug effect; a wide pulse pressure in aortic regurgitation, thyroid excess and anaemia; a narrow pulse pressure in aortic stenosis, tamponade and hypovolaemia.", { normal: "Below 140/90 mmHg in the clinic setting." }),
        item("bp_both_arms", "Blood pressure in both arms", "Measure in the other arm as well, at least once. A difference of more than 10 to 15 mmHg in systolic is abnormal.", "A difference between arms is seen in aortic dissection, subclavian stenosis, coarctation and Takayasu's arteritis.", d),
        item("postural_bp", "Postural (orthostatic) blood pressure", "Measure lying after 5 minutes, then standing at 1 and 3 minutes. A fall of 20 mmHg or more in systolic or 10 mmHg or more in diastolic, or symptoms on standing, is abnormal.", "A postural drop is seen in hypovolaemia, blood loss, autonomic neuropathy (diabetes, Parkinson's), adrenal insufficiency and with antihypertensive or diuretic drugs.", d),
        item("resp_rate", "Respiratory rate and pattern", "Count breaths for a full minute while appearing to feel the pulse, so the patient does not alter breathing. Note depth, regularity, use of accessory muscles, and any pattern: deep and sighing, periodic with pauses, or gasping.", "Fast breathing is seen in pneumonia, heart failure, acidosis, anxiety and pain; deep sighing (Kussmaul) breathing in metabolic acidosis; periodic (Cheyne-Stokes) breathing in heart failure, brainstem lesions and opioid effect; slow breathing in opioid or sedative overdose and raised intracranial pressure.", { normal: "12 to 20 per minute, regular, no accessory muscle use." }),
        item("temperature", "Temperature", "Use a digital thermometer in the axilla for at least a minute, or oral if the patient can hold it under the tongue with the mouth closed. Record the site, value and time; note the pattern over the chart (continuous, remittent, intermittent, relapsing).", "A continuous fever is seen in enteric fever and pneumonia; an intermittent fever with chills in malaria, urinary sepsis and abscess; a relapsing pattern in some infections and lymphoma; a low temperature in sepsis of the elderly, hypothyroidism and exposure.", { normal: "36.5 to 37.5 °C." }),
        item("spo2", "Oxygen saturation", "Place the probe on a warm, clean finger without nail polish; wait for a stable waveform. Record the value and whether on room air or oxygen (and the flow).", "Low saturation is seen in pneumonia, pulmonary oedema, pulmonary embolism, severe airway disease and shunts; the reading is unreliable with cold hands, poor perfusion, nail polish and carbon monoxide poisoning.", { normal: "Above 94% on room air." }),
        item("capillary_refill", "Capillary refill time", "Press on the nail bed or sternum for 5 seconds at heart level, release, and time the return of colour.", "A refill time longer than 2 seconds is seen in shock, dehydration and cold peripheries.", { normal: "Under 2 seconds." }),
        item("pain_score", "Pain score", "Ask the patient to rate current pain from 0 (none) to 10 (worst imaginable), and where.", "A recorded score allows the response to analgesia and the trend of the illness to be followed rather than guessed.", d),
      ],
    },
    {
      id: "anthropometry",
      title: "Anthropometry",
      items: [
        item("weight_height_bmi", "Weight, height and BMI", "Weigh on a calibrated scale in light clothing; measure height standing straight without footwear. BMI = weight in kilograms divided by height in metres squared. Use the Asian-Indian cut-offs: overweight from 23, obese from 25.", "Low BMI is seen in undernutrition, tuberculosis, malignancy and chronic disease; raised BMI in metabolic syndrome; an unexplained fall in weight over weeks always needs explaining.", { normal: "BMI 18.5 to 22.9 (Asian-Indian range)." }),
        item("waist", "Waist circumference", "Measure at the midpoint between the lowest rib and the iliac crest, at the end of a normal expiration, tape horizontal. Cut-offs for Asian Indians: 90 cm men, 80 cm women.", "Central obesity is seen with insulin resistance, diabetes, fatty liver and cardiovascular risk independent of BMI.", d),
        item("mid_arm", "Mid-upper-arm circumference", "Measure the left arm hanging relaxed, at the midpoint between acromion and olecranon.", "A low mid-arm circumference is seen in protein-energy malnutrition and is useful when weight cannot be measured (bedbound, oedematous).", d),
        item("arm_span", "Arm span and segments", "Measure fingertip to fingertip with arms outstretched horizontally; compare with height. Upper segment is crown to pubic symphysis; lower segment is symphysis to floor.", "Arm span exceeding height by more than 5 cm, or a low upper-to-lower segment ratio, is seen in Marfan's syndrome and hypogonadism (eunuchoid habitus).", d),
      ],
    },
    {
      id: "piccle",
      title: "Pallor, icterus, cyanosis, clubbing, koilonychia, lymphadenopathy, oedema",
      intro: "The seven bedside signs every long case records, in daylight where possible.",
      items: [
        item("pallor", "Pallor", "In daylight, gently pull down the lower eyelid and compare the colour of the palpebral conjunctiva with your own; look also at the tongue, palate, nail beds and palmar creases. Grade as absent, mild, moderate or severe.", "Pallor is seen in anaemia of any cause (iron deficiency, chronic disease, haemolysis, blood loss, marrow failure), and also in shock and vasoconstriction without anaemia; pale palmar creases point to a markedly low haemoglobin.", { normal: "No pallor." }),
        item("icterus", "Icterus", "In daylight, ask the patient to look down while you lift the upper eyelid and inspect the upper bulbar sclera; also look under the tongue and at the skin. Do not rely on artificial light.", "Scleral yellowing is seen when bilirubin rises: hepatitis, obstruction of the bile ducts, haemolysis, sepsis, drug injury and chronic liver disease. A yellow skin with white sclera is seen with carotene, not bilirubin.", { normal: "No icterus." }),
        item("cyanosis_central", "Cyanosis — central", "Look at the tongue, lips and inner cheeks in good light. Bluish discolouration of the tongue means central cyanosis.", "Central cyanosis is seen in severe lung disease, right-to-left cardiac shunts, pulmonary oedema, massive pulmonary embolism and methaemoglobinaemia; it needs a large amount of deoxygenated haemoglobin, so it may be absent in severe anaemia and prominent in polycythaemia.", { normal: "No cyanosis." }),
        item("cyanosis_peripheral", "Cyanosis — peripheral", "Look at the nail beds, fingertips, toes, ear lobes and tip of the nose with a pink tongue.", "Peripheral cyanosis alone is seen with cold exposure, poor peripheral circulation, shock, venous obstruction and Raynaud's phenomenon.", d),
        item("clubbing", "Clubbing", "Look at the finger from the side at eye level: loss of the angle between the nail and the nail fold (normally about 160 degrees), then a spongy fluctuant nail bed (press the base of the nail and rock it), then increased curvature, then a drumstick fingertip. Schamroth's sign: place the nails of the two index fingers back to back; the normal diamond-shaped window disappears in clubbing. Check the toes too.", "Clubbing is seen in lung cancer, bronchiectasis, lung abscess, empyema, interstitial lung disease, cyanotic congenital heart disease, infective endocarditis, cirrhosis, inflammatory bowel disease and coeliac disease. Simple pulmonary tuberculosis and uncomplicated asthma or COPD do not usually cause clubbing.", { normal: "No clubbing." }),
        item("koilonychia", "Koilonychia", "Look at the fingernails from the side: a concave, spoon-shaped, thin nail that could hold a drop of water. Distinguish from a flat nail (platynychia).", "Spoon nails are seen in long-standing iron deficiency; also occasionally with occupational trauma and fungal infection.", { normal: "No koilonychia." }),
        item("lymph_nodes", "Lymphadenopathy", "Examine from behind for the neck: submental, submandibular, pre- and post-auricular, occipital, anterior and posterior cervical chains, supraclavicular. Then axillary (support the patient's arm, roll your fingers against the chest wall for the apical, medial, lateral, anterior and posterior groups), epitrochlear (above the medial epicondyle), and inguinal (horizontal and vertical groups). For any node record site, size, number, consistency (soft, firm, rubbery, hard), tenderness, matting, fixity to skin or deep structures, and overlying skin.", "Tender soft nodes are seen with local infection; rubbery matted nodes with tuberculosis; rubbery discrete generalised nodes with lymphoma; hard fixed nodes with metastatic carcinoma; a left supraclavicular node with abdominal malignancy; generalised nodes also with HIV, infectious mononucleosis and some drug reactions.", { normal: "No palpable lymphadenopathy." }),
        item("oedema", "Oedema", "Press firmly with the thumb for 10 to 15 seconds over the medial malleolus, the shin, and the sacrum in a bedbound patient; a pit that persists is pitting oedema. Note the level it reaches (ankle, knee, thigh, sacrum, abdominal wall, face), whether both sides are equal, and whether the face and eyelids are puffy on waking.", "Bilateral pitting oedema is seen in heart failure, kidney disease, liver disease, low albumin, severe anaemia, thiamine deficiency and with calcium-channel blockers; facial puffiness in the morning points to a renal cause; unilateral oedema to venous thrombosis, cellulitis or lymphatic obstruction; non-pitting oedema to thyroid deficiency and chronic lymphoedema.", { normal: "No pedal oedema." }),
      ],
    },
    {
      id: "hydration",
      title: "Hydration and volume status",
      intro: "Combine several signs; no single sign is reliable on its own. Postural pulse rise and dry axillae are the most useful bedside signs of hypovolaemia in adults.",
      items: [
        item("tongue_mucosa", "Tongue and mucous membranes", "Look at the tongue and the inside of the cheeks and lips. A dry tongue with longitudinal furrows suggests fluid loss, but mouth breathing also dries the tongue.", "Dry mucosae are seen in dehydration from diarrhoea, vomiting, fever, poor intake and diuresis.", { normal: "Moist tongue." }),
        item("skin_turgor", "Skin turgor", "Pinch a fold of skin over the sternum, forearm or abdomen and release; note how quickly it flattens. Skin over the clavicle is more reliable in the elderly, where turgor is normally reduced.", "Slow return of the skin fold is seen in significant fluid loss; the sign lags behind and is unreliable in the elderly and in wasted patients.", d),
        item("sunken_eyes", "Sunken eyes and cold peripheries", "Look for sunken eyes and reduced eyeball tension; feel the hands and feet and note where the temperature changes from warm to cold along the limb.", "Sunken eyes are seen in severe fluid loss; cold peripheries with a proximal temperature line in shock and poor perfusion.", d),
        item("axillae", "Axillary moisture", "Feel both axillae for sweat with the back of the fingers.", "Dry axillae are seen in hypovolaemia; the sign has a useful positive likelihood ratio in adults.", d),
        item("jvp", "Jugular venous pressure", "Patient reclining at 45 degrees, head turned slightly to the left, good tangential light. Look for the internal jugular pulsation between the two heads of the sternocleidomastoid. Measure the vertical height of the top of the pulsation above the sternal angle. Distinguish from the carotid: the venous pulse has a double waveform per beat, is not palpable, falls on inspiration and sitting up, and rises on pressing over the liver (hepatojugular reflux).", "A raised JVP is seen in right heart failure, fluid overload, tricuspid valve disease, constrictive pericarditis and tamponade; a rise on inspiration (Kussmaul's sign) in constriction and right ventricular infarction; a low or invisible JVP in hypovolaemia.", { normal: "Not raised (under 3 to 4 cm above the sternal angle)." }),
        item("urine_output", "Urine output", "Ask when urine was last passed, roughly how much, and its colour; read the chart or the catheter bag if present. Record the volume per hour or per shift rather than an impression.", "Reduced output with dark urine is seen in dehydration and shock; reduced output despite good hydration in acute kidney injury and obstruction.", d),
      ],
    },
    {
      id: "skin_hair_nails",
      title: "Skin, hair and nails",
      items: [
        item("skin_colour", "Skin colour and pigmentation", "Inspect exposed and covered skin for generalised or patchy change: darkening of creases, knuckles, scars, buccal mucosa and pressure points; loss of pigment; a slate-grey or bronze tinge.", "Pigmentation of creases and mucosa is seen in adrenal insufficiency and with some drugs; bronze pigmentation in iron overload; patchy depigmentation in vitiligo, associated with autoimmune thyroid and adrenal disease; a sallow lemon tint in chronic kidney disease.", d),
        item("rash", "Rash", "Describe any rash by distribution, morphology (macule, papule, vesicle, pustule, wheal, plaque), colour, and whether it blanches on pressure through a glass slide.", "A non-blanching petechial or purpuric rash is seen in meningococcal sepsis, dengue, low platelets and vasculitis; a blanching maculopapular rash in viral illness, drug reaction and dengue; target lesions in erythema multiforme; a butterfly facial rash in lupus.", { normal: "No rash." }),
        item("petechiae_bruising", "Petechiae, purpura and bruising", "Look at the shins, forearms, palate and around a blood-pressure cuff or tourniquet site. Petechiae are pinpoint, purpura larger, ecchymoses bruise-sized. A tourniquet test counts petechiae in a marked square after inflating a cuff midway between systolic and diastolic for 5 minutes.", "Petechiae and easy bruising are seen in thrombocytopenia (dengue, immune thrombocytopenia, marrow failure), vasculitis, scurvy, steroid use and clotting disorders.", d),
        item("spider_naevi", "Spider naevi and palmar erythema", "Look over the face, neck, upper chest, back and arms (the drainage area of the superior vena cava) for a central red spot with radiating vessels that blanches on pressing the centre and refills from the centre outwards. Look at the palms for redness over the thenar and hypothenar eminences.", "More than two or three spider naevi, and palmar erythema, are seen in chronic liver disease and also in pregnancy, thyroid excess and rheumatoid arthritis.", d),
        item("xanthoma", "Xanthomas and xanthelasma", "Look for yellow plaques on the eyelids near the inner canthus, nodules over tendons (Achilles, extensor tendons of the hand), and eruptive papules over extensor surfaces.", "Tendon xanthomas are seen in familial hypercholesterolaemia; eruptive xanthomas in very high triglycerides; xanthelasma in lipid disorders and also in people with normal lipids.", d),
        item("scars_marks", "Scars, injection marks and tattoos", "Note surgical scars and their site, old sinuses, healed ulcers, injection marks along veins, and scarification or branding marks from traditional treatment.", "Injection marks are seen in intravenous drug use (endocarditis, hepatitis, HIV risk); scars of previous surgery explain adhesions and stomas; a healed scrofula scar in the neck points to past tuberculous nodes.", d),
        item("hair", "Hair", "Note scalp hair texture, thinning or patchy loss, loss of the outer third of the eyebrows, and the distribution of body hair (axillary, pubic, facial) against sex and age.", "Sparse dry hair and loss of the lateral eyebrows is seen in thyroid deficiency; loss of axillary and pubic hair in hypopituitarism, cirrhosis and hypogonadism; excess facial hair in women in polycystic ovary syndrome, Cushing's and androgen excess; patchy loss in alopecia areata and fungal infection.", d),
        item("nail_changes", "Other nail changes", "Look for white nails (leukonychia), half-and-half nails, pitting, transverse ridges or grooves, splinter haemorrhages under the nail, brittle or fungal nails, and the nail-fold capillaries.", "White nails are seen in low albumin (liver and kidney disease); half-and-half nails in chronic kidney disease; pitting in psoriasis; transverse grooves (Beau's lines) after a severe illness; splinter haemorrhages in infective endocarditis, vasculitis and trauma.", d),
      ],
    },
    {
      id: "head_eyes_mouth",
      title: "Head, face, eyes and mouth",
      items: [
        item("face_puffiness", "Facial puffiness and asymmetry", "Look for puffiness of the eyelids and face, especially in the morning, and for asymmetry of the nasolabial folds and eyelid closure on smiling and shutting the eyes.", "Periorbital puffiness is seen in nephrotic syndrome, acute nephritis, thyroid deficiency, angioedema and superior vena cava obstruction; facial asymmetry in facial nerve palsy and stroke.", d),
        item("parotid", "Parotid and salivary glands", "Look and feel in front of and below the ear lobe for enlargement, comparing sides; feel the submandibular glands under the jaw.", "Bilateral parotid swelling is seen in mumps, chronic alcohol use, malnutrition, diabetes and HIV; a unilateral hard gland in tumour.", d),
        item("eyes_lids", "Eyelids and eye position", "Look for drooping of an upper lid (ptosis), retraction of the lids with visible sclera above the iris, lid lag on looking down, and forward protrusion of the eyeball seen from above and behind.", "Ptosis is seen in third nerve palsy, Horner's syndrome, myasthenia gravis and old age; lid retraction and lid lag with exophthalmos in thyroid eye disease.", d),
        item("conjunctiva_sclera", "Conjunctiva and sclera", "Beyond pallor and icterus, look for redness, suffusion (red without discharge), chemosis, subconjunctival haemorrhage, blue sclera, and pinguecula or pterygium.", "Conjunctival suffusion is seen in leptospirosis and some viral fevers; red eye with discharge in conjunctivitis; blue sclera in osteogenesis imperfecta and iron deficiency; subconjunctival haemorrhage with coughing, trauma and bleeding disorders.", d),
        item("cornea_iris", "Cornea and iris", "Look at the corneal margin for a grey-white ring (arcus), and at the limbus in good light or with a torch from the side for a brown-green ring at the periphery of the cornea.", "A corneal arcus is seen with age and, in the young, with high cholesterol; a Kayser-Fleischer ring is seen in Wilson's disease and needs slit-lamp confirmation.", d),
        item("pupils", "Pupils", "Compare size and shape; test the direct and consensual reaction to a torch shone from the side, and the near reaction.", "Pinpoint pupils are seen in opioid or organophosphate poisoning and pontine lesions; dilated fixed pupils in brain-stem death, atropine-like drugs and third nerve palsy; unequal pupils in Horner's syndrome and uncal herniation.", d),
        item("lips_mouth", "Lips and angles of the mouth", "Look for cracking at the angles, pale or blue lips, ulcers, pigmented spots on the lips and buccal mucosa, and swelling.", "Angular stomatitis is seen in iron, riboflavin and B12 deficiency and with ill-fitting dentures; peri-oral pigmented spots in Peutz-Jeghers syndrome; swollen lips in angioedema.", d),
        item("tongue", "Tongue", "Ask the patient to put the tongue out and move it side to side; look at colour, coating, papillae, moisture, ulcers, size, fasciculations and deviation.", "A smooth pale bald tongue is seen in iron and B12 deficiency; a beefy red tongue in B12 and niacin deficiency; a large tongue in acromegaly, amyloidosis and thyroid deficiency; deviation to one side in hypoglossal nerve palsy; wasting with fasciculations in motor neurone disease; white plaques that scrape off in candidiasis (HIV, diabetes, steroids, antibiotics).", d),
        item("gums_teeth", "Gums, teeth and oral hygiene", "Look at the gums for bleeding, swelling, a blue line at the margin, and receding; note dental caries, missing teeth and dentures.", "Bleeding swollen gums are seen in scurvy, leukaemia and phenytoin use; a blue line in lead poisoning; poor dentition and caries are a source of endocarditis and lung abscess.", d),
        item("palate_tonsils_pharynx", "Palate, tonsils and pharynx", "With a torch and tongue depressor, look at the hard and soft palate for petechiae, high arch, ulcers and pigmentation, and at the tonsils and posterior pharyngeal wall for enlargement, exudate and membrane. Ask the patient to say 'ah' and watch the uvula rise centrally.", "Palatal petechiae are seen in infectious mononucleosis and thrombocytopenia; a high-arched palate in Marfan's habitus; tonsillar exudate in streptococcal and viral pharyngitis; a grey adherent membrane in diphtheria; deviation of the uvula in vagal palsy or a peritonsillar abscess.", d),
        item("oral_ulcers", "Oral ulcers", "Look inside the cheeks, under the tongue and on the gums for ulcers; note number, size, pain and whether they recur.", "Painful recurrent small ulcers are seen in aphthous stomatitis, Behçet's disease, coeliac and inflammatory bowel disease; painless ulcers in lupus and syphilis; large persistent ulcers in malignancy.", d),
      ],
    },
    {
      id: "neck",
      title: "Neck",
      items: [
        item("thyroid", "Thyroid", "Stand behind the seated patient. Inspect from the front with the neck slightly extended and ask the patient to swallow a sip of water: a thyroid swelling rises with swallowing. Palpate with both hands, fingertips on either side of the trachea below the cricoid, again during swallowing. Note size, symmetry, surface (smooth or nodular), consistency, tenderness, mobility, the lower border (can you get below it?) and a thrill. Percuss over the upper sternum for retrosternal extension and auscultate for a bruit. Feel for cervical nodes. Ask the patient to raise both arms above the head for a minute and watch for facial flushing or distress (Pemberton's sign).", "A diffuse smooth goitre is seen in iodine deficiency, Graves' disease and Hashimoto's thyroiditis; a multinodular goitre in long-standing iodine deficiency; a single hard fixed nodule with nodes raises concern for carcinoma; a bruit in Graves' disease; a tender gland in thyroiditis; Pemberton's sign in retrosternal extension.", { normal: "Thyroid not enlarged." }),
        item("trachea", "Trachea", "With the patient looking straight ahead, place the tip of the index finger in the suprasternal notch and feel the tracheal rings; judge whether the trachea is central or shifted, and whether it tugs downward with each heartbeat.", "Tracheal shift is seen towards a collapsed lung or fibrosis and away from a large effusion, pneumothorax or mass; a tracheal tug in an aortic arch aneurysm.", d),
        item("carotids", "Carotid arteries", "Palpate each carotid separately, gently, at the level of the thyroid cartilage medial to the sternocleidomastoid; never both at once. Auscultate with the bell during breath-holding for a bruit.", "A carotid bruit is seen with carotid stenosis and in transmitted aortic murmurs; unequal carotid pulses in dissection and Takayasu's arteritis.", d),
        item("neck_veins", "Neck veins and superior vena cava signs", "Beyond the JVP, look for distended non-pulsatile neck veins and dilated veins over the upper chest, facial swelling and plethora, worse on lying flat or raising the arms.", "Distended non-pulsatile neck veins with facial and arm swelling are seen in superior vena cava obstruction, most often from lung cancer or lymphoma.", d),
        item("neck_stiffness", "Neck stiffness", "With the patient supine and no pillow, gently flex the neck so the chin approaches the chest; resistance or pain is neck stiffness. Look for spontaneous hip and knee flexion during neck flexion. Then with hip and knee flexed to 90 degrees, extend the knee; resistance or pain in the hamstring is a positive Kernig's sign.", "Neck stiffness and Kernig's sign are seen in meningitis, subarachnoid haemorrhage and other meningeal irritation; they may be absent in the elderly, the immunosuppressed and in deep coma.", { normal: "No neck stiffness." }),
      ],
    },
    {
      id: "hands",
      title: "Hands",
      intro: "Shake hands and hold them for a moment: temperature, moisture, tremor, grip and muscle bulk all show themselves in that time.",
      items: [
        item("hand_temperature", "Temperature and sweating of the hands", "Feel both palms with the back of your fingers; note whether warm and moist, warm and dry, cold and clammy, or cold and dry.", "Warm moist hands are seen in thyroid excess and carbon dioxide retention; cold clammy hands in shock, anxiety and hypoglycaemia; cold dry hands in thyroid deficiency and poor circulation.", d),
        item("fine_tremor", "Fine tremor", "Ask the patient to hold both arms outstretched with fingers spread; lay a sheet of paper over the fingers to make a fine tremor visible.", "A fine postural tremor is seen in thyroid excess, anxiety, alcohol withdrawal and with salbutamol or caffeine; a coarse resting pill-rolling tremor in Parkinsonism; an intention tremor in cerebellar disease.", d),
        item("flapping_tremor", "Flapping tremor (asterixis)", "Ask the patient to stretch out the arms and dorsiflex the wrists with fingers spread, and hold for 15 to 30 seconds. Watch for irregular jerky flaps at the wrist; alternatively hold the patient's hands and feel the sudden loss of tone.", "A flapping tremor is seen in hepatic encephalopathy, carbon dioxide retention and uraemia.", { normal: "No flapping tremor." }),
        item("dupuytren", "Dupuytren's contracture", "Look and feel over the palm for a thickened cord along the tendon to the ring or little finger, with the finger held in flexion.", "Dupuytren's contracture is seen in chronic alcohol use and cirrhosis, diabetes, epilepsy treatment, manual work and as a familial trait.", d),
        item("small_muscle_wasting", "Wasting of the small muscles of the hand", "Compare the thenar and hypothenar eminences and the spaces between the metacarpals on the back of the hand on both sides; note guttering.", "Wasting of the small hand muscles is seen in ulnar and median nerve lesions, lower brachial plexus and T1 root lesions, motor neurone disease, syringomyelia and leprosy.", d),
        item("joints_hand", "Joints and deformities of the hand", "Look for swelling, redness and deformity at the wrist, knuckles and finger joints; feel for warmth and tenderness; note bony nodules at the distal or proximal finger joints and ulnar drift of the fingers.", "Symmetrical swelling of the knuckles and proximal finger joints with ulnar deviation is seen in rheumatoid arthritis; bony nodules at the finger joints in osteoarthritis; swelling of the distal joints with nail pitting in psoriatic arthritis; a tophus in gout.", d),
        item("endocarditis_signs", "Peripheral signs of endocarditis", "Look at the fingers and toes for tender raised nodules on the pulps (Osler's nodes), painless red macules on the palms and soles (Janeway lesions), and splinter haemorrhages under the nails.", "These signs are seen in infective endocarditis and occasionally in vasculitis and lupus; their absence does not exclude endocarditis.", d),
        item("palmar_creases", "Palmar creases", "Ask the patient to hyperextend the fingers so the palmar creases open; look at their colour and at the skin of the palm for pigmentation.", "Pale creases are seen in marked anaemia; pigmented creases in adrenal insufficiency; a single transverse palmar crease in Down's syndrome.", d),
      ],
    },
    {
      id: "trunk_limbs_survey",
      title: "Trunk, spine and limbs — quick survey",
      intro: "A short look before the system examinations, so that a sign outside the presenting system is not missed.",
      items: [
        item("chest_wall", "Chest wall shape", "Inspect from the front, side and behind for a barrel chest, a depressed sternum, a prominent sternum, rib deformity and asymmetry of movement.", "A barrel chest is seen in emphysema; a pigeon chest in childhood rickets and long-standing asthma; a rachitic rosary in rickets; asymmetric movement in effusion, collapse and pneumothorax.", d),
        item("gynaecomastia", "Gynaecomastia", "In a man, inspect the breasts and feel for firm glandular tissue under the nipple between thumb and fingers, distinguishing it from soft fat.", "Gynaecomastia is seen in cirrhosis, hypogonadism, thyroid excess, testicular and other tumours, and with drugs such as spironolactone, digoxin, antiandrogens and some antiretrovirals.", d),
        item("spine", "Spine", "With the patient standing, look from behind and the side for kyphosis, scoliosis and loss of lumbar lordosis; ask the patient to bend forward and touch the toes; percuss each spinous process gently for tenderness; note any localised swelling or gibbus.", "A localised gibbus with spinal tenderness is seen in tuberculosis of the spine; an exaggerated kyphosis in osteoporosis and ankylosing spondylitis; scoliosis in neuromuscular disease and adolescence.", d),
        item("secondary_sexual", "Secondary sexual characteristics", "Note facial, axillary and pubic hair, breast development, voice, and testicular size if relevant to the presentation and with consent.", "Loss of secondary sexual characteristics is seen in hypogonadism, hypopituitarism, cirrhosis and haemochromatosis; hirsutism and virilisation in androgen excess.", d),
        item("lower_limb_vessels", "Lower limb veins and arteries", "Standing, look for varicose veins and venous eczema; lying, feel the calves for tenderness and swelling, compare calf circumference 10 cm below the tibial tuberosity, feel skin temperature and the pulses, and look for hair loss, shiny skin and ulcers on the feet.", "Unilateral calf swelling and tenderness are seen in deep vein thrombosis; hairless shiny skin with weak pulses and punched-out painful ulcers in arterial disease; venous eczema and ulcers above the medial malleolus in venous insufficiency.", d),
        item("diabetic_foot", "Feet (with attention to the diabetic foot)", "Remove footwear. Look between the toes and under the heel for cracks, ulcers, callus and fungal infection; feel the pulses; test light touch with a monofilament or cotton wool and vibration with a tuning fork at the big toe; note deformity of the toes or the arch.", "Loss of protective sensation with dry cracked skin, callus and deformity is seen in diabetic neuropathy and precedes ulceration; a warm swollen deformed foot without pain in Charcot arthropathy.", d),
        item("pressure_areas", "Pressure areas", "In a bedbound or immobile patient, inspect the sacrum, heels, hips, elbows and occiput for redness that does not blanch, blistering or ulceration, and record the grade.", "Pressure injury is seen in immobility, poor nutrition, incontinence and reduced sensation; a non-blanching red area is the first stage and reversible.", d),
        item("involuntary_movements", "Involuntary movements", "Watch the face, trunk and limbs at rest and during conversation for tremor, jerks, writhing, restlessness of the legs, tics and fasciculations.", "Chorea is seen in rheumatic fever, Huntington's disease and with dopamine-blocking drugs; myoclonic jerks in metabolic encephalopathy and epilepsy; fasciculations in motor neurone disease; restless legs with iron deficiency and kidney disease.", d),
        item("odour_bedside", "Bedside environment", "Look at the sputum cup, vomit bowl, urine bag or bedpan, oxygen flow, drips, monitors and medicine packets at the bedside before they are cleared away.", "Rusty or purulent sputum, coffee-ground vomit, tea-coloured urine, or an inhaler by the bed each point the examination in a direction the history may not have mentioned.", d),
      ],
    },
  ],
};
